# Copyright 2010-2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# This file is licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License. A copy of
# the License is located at
#
# http://aws.amazon.com/apache2.0/
#
# This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
# CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Original version:
# https://github.com/aws-samples/codepipeline-nested-cfn

Parameters:
  AMBAppsSAMBucketName:
    AllowedPattern: (?!^(\d{1,3}\.){3}\d{1,3}$)(^[a-z0-9]([a-z0-9-]*(\.[a-z0-9])?)*$)
    Description: Name for s3 bucket to use for SAM application deployment. Keep it short, because it will be transformed into ${AMBAppsSAMBucketName}-${AMBAppsRegion}-${AWS::AccountId}
    Type: String
    Default: amb-apps-build
Resources:
  SAMArtifactStoreBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${AMBAppsSAMBucketName}-${AWS::Region}-${AWS::AccountId}"
      PublicAccessBlockConfiguration: 
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: AMBApps
          Value: AMBAppsSAMArtifactStoreS3
  SAMArtifactStoreBucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref SAMArtifactStoreBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Join
              - ""
              - - !GetAtt SAMArtifactStoreBucket.Arn
                - /*
            Condition:
              StringNotEquals:
                "s3:x-amz-server-side-encryption": "aws:kms"
          - Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: !Join
              - ""
              - - !GetAtt SAMArtifactStoreBucket.Arn
                - /*
            Condition:
              Bool:
                "aws:SecureTransport": false
Outputs:
  SAMArtifactStoreBucketName:
    Description: The name of S3 bucket with deployment artifacts of SAM application
    Value: !Ref SAMArtifactStoreBucket
    Export:
      Name: !Sub "${AWS::StackName}-SAMArtifactStoreBucketName"
