# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  amb-apps-lambdas

  Sample SAM Template for amb-apps-lambdas
Parameters:
  AMBAppsLambdaNamePrefix:
    Type: String
    Description: >
      Prefix of the all lambda functions names.
  AMBAppsSecurityGroupID:
    Type: String
    Description: >
      ID if the security group associated with the AMBAppsPrivateSubnetID to use for Lambda function interacting with
      AMB-managed Hyperledger Fabric.
  AMBAppsPrivateSubnet1ID:
    Type: String
    Description: >
      ID if the private subnet with connectivity with AMB service. Lambda functions interacting with Hyperledger Fabric
      managed by AMB will be instantiated in that network.
  AMBAppsPrivateSubnet2ID:
    Type: String
    Description: >
      ID if the private subnet with connectivity with AMB service. Lambda functions interacting with Hyperledger Fabric
      managed by AMB will be instantiated in that network.
  AMBAppsPrivateSubnet3ID:
    Type: String
    Description: >
      ID if the private subnet with connectivity with AMB service. Lambda functions interacting with Hyperledger Fabric
      managed by AMB will be instantiated in that network.
  AMBAppsInvokeQueryFcnReservedConcurrency:
    Type: Number
    Description: >
      A reserved concurrency for Invoke and Query Lambda function to throttle transactions input to AMB service
    Default: 34
  AMBAppsSAMRoleARN:
    Type: String
    Description: >
      ARN of an IAM role for SAM application.
Conditions:
  SecondPrivateSubnetExists:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref AMBAppsPrivateSubnet2ID
  ThirdPrivateSubnetExists:
    Fn::Not:
      - Fn::Equals:
          - ""
          - !Ref AMBAppsPrivateSubnet3ID
  # AMBAppsPrivateSubnetID:
  #   Type: String
  #   Description: >
  #     ID if the private subnet with connectivity with AMB service. Lambda functions interacting with Hyperledger Fabric
  #     managed by AMB will be instantiated in that network.
  # AMBAppsSecurityGroupID:
  #   Type: String
  #   Description: >
  #     ID if the security group associated with the AMBAppsPrivateSubnetID to use for Lambda function interacting with
  #     AMB-managed Hyperledger Fabric.
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs10.x
    Timeout: 180
    Handler: index.handler
Resources:
  devopsDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: !Sub "${AMBAppsLambdaNamePrefix}-dependencies"
      Description: Dependencies for sam app [node_modules, lib]
      ContentUri: ../dependencies/
      CompatibleRuntimes:
        - nodejs10.x
      LicenseInfo: "Apache2"
      RetentionPolicy: Delete
  #####
  # Lambdas using Hyperledger Fabric Client:
  #
  invokequerychaincode:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: !Sub "${AMBAppsLambdaNamePrefix}-invoke-query-chaincode"
      Runtime: nodejs10.x
      CodeUri: fcn-invoke-query-chaincode/
      Description: "Lambda function that helps to trigger invoke or query chaincode functions"
      MemorySize: 512
      Timeout: 300
      Role: !Ref AMBAppsSAMRoleARN
      ReservedConcurrentExecutions: !Ref AMBAppsInvokeQueryFcnReservedConcurrency
      Layers:
        - !Ref devopsDependenciesLayer
      VpcConfig:
        SecurityGroupIds:
          #- !Ref AMBAppsSecurityGroupID
          - !Ref AMBAppsSecurityGroupID
        SubnetIds:
          - !Ref AMBAppsPrivateSubnet1ID
          - Fn::If:
              - SecondPrivateSubnetExists
              - !Ref AMBAppsPrivateSubnet2ID
              - !Ref "AWS::NoValue"
          - Fn::If:
              - ThirdPrivateSubnetExists
              - !Ref AMBAppsPrivateSubnet3ID
              - !Ref "AWS::NoValue"
      Tags:
        AMBApps: LambdaInvokeQueryChaincode
        UseHFC: true
Outputs:
  # AMBAppsIamRole:
  #   Description: "Implicit IAM Role created for  AMB Apps SAM application"
  #   Value: !GetAtt AMBAppsRole.Arn
  #   Export:
  #     Name: !Sub "${AWS::StackName}-AMBAppsRoleARN"
  AMBAppsInvokeQueryFunctionARN:
    Description: ARN of Invoke-query lambda function
    Value: !GetAtt invokequerychaincode.Arn
    Export:
      Name: !Sub "${AWS::StackName}-InvokeQueryFunctionARN"
  AMBAppsDepsLayerARN:
    Description: ARN of Invoke-query lambda function
    Value: !Ref devopsDependenciesLayer
    Export:
      Name: !Sub "${AWS::StackName}-DepsLayerARN"
