# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# A copy of the License is located at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# or in the "license" file accompanying this file. This file is distributed
# on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language governing
# permissions and limitations under the License.

version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - cp -r $CODEBUILD_SRC_DIR_LIBS/lib .
      - cp $CODEBUILD_SRC_DIR_CONFIG/setConfigVariables.sh ./devops
      # - $(aws ecr get-login --no-include-email)
      # - TAG="synch$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      # - IMAGE_URI="${ECR_REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - ./devops/build.sh
      - ./devops/deploy.sh
  # post_build:
  #   commands:
  #     - docker push "$IMAGE_URI"
  #     - docker tag "$IMAGE_URI" "${ECR_REPOSITORY_URI}:latest"
  #     - docker push "${ECR_REPOSITORY_URI}:latest"
  #     - printf '[{"name":"amb-app-the-synchronizer-container","imageUri":"%s"}]' "$IMAGE_URI" > images.json
artifacts:
  files: images.json
