#!/bin/bash

if test -f "./devops/setConfigVariables.sh"; then
    source ./devops/setConfigVariables.sh
fi

if test -f "./setConfigVariables.sh"; then
    source ./setConfigVariables.sh
fi

# export AMB_DEVOPS_IAM_ROLES_STACK_NAME=amb-devops-iam-roles
# export AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_NAME=amb-devops-cloudwatch-role
# export AMB_DEVOPS_CODEBUILD_IAM_ROLE_NAME=amb-devops-codebuild-role
# export AMB_DEVOPS_SAM_IAM_ROLE_NAME=amb-devops-sam-role

echo "Creating necessary IAM roles for DevOps part of Jumpstart Kit:"
echo "AMB_DEVOPS_REGION="$AMB_DEVOPS_REGION
echo "AMB_DEVOPS_IAM_ROLES_STACK_NAME="$AMB_DEVOPS_IAM_ROLES_STACK_NAME
echo "AMB_DEVOPS_IAM_PERMISSIONS_BOUNDARY="$AMB_DEVOPS_IAM_PERMISSIONS_BOUNDARY

# CodeBuild roles
echo "AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_NAME="$AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_NAME
echo "AMB_DEVOPS_CODEBUILD_IAM_ROLE_NAME="$AMB_DEVOPS_CODEBUILD_IAM_ROLE_NAME

# SAM applicaiton role
echo "AMB_DEVOPS_SAM_IAM_ROLE_NAME="$AMB_DEVOPS_SAM_IAM_ROLE_NAME

echo "AMB_DEVOPS_STACK_PREFIX="$AMB_DEVOPS_STACK_PREFIX
echo "AMB_DEVOPS_LAMBDA_PREFIX="$AMB_DEVOPS_LAMBDA_PREFIX
echo "AMB_DEVOPS_IAM_ROLES_PREFIX="$AMB_DEVOPS_IAM_ROLES_PREFIX
echo "AMB_DEVOPS_IAM_POLICIES_PREFIX="$AMB_DEVOPS_IAM_POLICIES_PREFIX
echo "AMB_DEVOPS_CHANNEL_S3_BUCKET_NAME_PREFIX="$AMB_DEVOPS_CHANNEL_S3_BUCKET_NAME_PREFIX
echo "AMB_APPS_BUILD_BUCKET_NAME_PREFIX="$AMB_APPS_BUILD_BUCKET_NAME_PREFIX
echo "AMB_DEVOPS_BUILD_BUCKET_NAME_PREFIX="$AMB_DEVOPS_BUILD_BUCKET_NAME_PREFIX
echo "AMB_DEVOPS_CODEBUILD_PROJECT_NAME="$AMB_DEVOPS_CODEBUILD_PROJECT_NAME
echo "AMB_DEVOPS_SNS_CW_ALARM_TOPIC_NAME_PREFIX="$AMB_DEVOPS_SNS_CW_ALARM_TOPIC_NAME_PREFIX
echo "AMB_DEVOPS_CW_STACKNAME_PREFIX="$AMB_DEVOPS_CW_STACKNAME_PREFIX

aws cloudformation deploy --region $AMB_DEVOPS_REGION --template-file ./devops/amb-devops-iam-roles-template.yaml --stack-name $AMB_DEVOPS_IAM_ROLES_STACK_NAME \
--parameter-overrides AMBDevopsRegion=$AMB_DEVOPS_REGION \
RepositoryName=$AMB_DEVOPS_REPOSITORY_NAME \
AMBDevOpsSAMRoleName=$AMB_DEVOPS_SAM_IAM_ROLE_NAME \
AMBDevOpsCloudWatchEventRoleName=$AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_NAME \
AMBDevOpsCodeBuildRoleName=$AMB_DEVOPS_CODEBUILD_IAM_ROLE_NAME \
BoundaryPolicyARN=$AMB_DEVOPS_IAM_PERMISSIONS_BOUNDARY \
StackPrefix=$AMB_DEVOPS_STACK_PREFIX \
LambdaPrefix=$AMB_DEVOPS_LAMBDA_PREFIX \
RolesPrefix=$AMB_DEVOPS_IAM_ROLES_PREFIX \
PoliciesPrefix=$AMB_DEVOPS_IAM_POLICIES_PREFIX \
ChannelS3BucketPrefix=$AMB_DEVOPS_CHANNEL_S3_BUCKET_NAME_PREFIX \
AMBAppsBuildBucketPrefix=$AMB_APPS_BUILD_BUCKET_NAME_PREFIX \
AMBDevOpsBuildBucketPrefix=$AMB_DEVOPS_BUILD_BUCKET_NAME_PREFIX \
AMBDevOpsCodeBuildProjectNamePrefix=$AMB_DEVOPS_CODEBUILD_PROJECT_NAME \
AMBDevOpsSNSCWAlarmTopicNamePrefix=$AMB_DEVOPS_SNS_CW_ALARM_TOPIC_NAME_PREFIX \
AMBDevOpsCloudWatchNamePrefix=$AMB_DEVOPS_CW_STACKNAME_PREFIX \
--capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset

export AMB_DEVOPS_SAM_IAM_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name $AMB_DEVOPS_IAM_ROLES_STACK_NAME --region $AMB_DEVOPS_REGION --query 'Stacks[0].Outputs[?OutputKey==`AMBDevOpsSAMRoleARN`].OutputValue' --output text)
echo "AMB_DEVOPS_SAM_IAM_ROLE_ARN="$AMB_DEVOPS_SAM_IAM_ROLE_ARN
export AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name $AMB_DEVOPS_IAM_ROLES_STACK_NAME --region $AMB_DEVOPS_REGION --query 'Stacks[0].Outputs[?OutputKey==`AMBDevOpsCloudWatchEventRoleARN`].OutputValue' --output text)
echo "AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_ARN="$AMB_DEVOPS_CLOUDWATCH_IAM_ROLE_ARN
export AMB_DEVOPS_CODEBUILD_IAM_ROLE_ARN=$(aws cloudformation describe-stacks --stack-name $AMB_DEVOPS_IAM_ROLES_STACK_NAME --region $AMB_DEVOPS_REGION --query 'Stacks[0].Outputs[?OutputKey==`AMBDevOpsCodeBuildRoleARN`].OutputValue' --output text)
echo "AMB_DEVOPS_CODEBUILD_IAM_ROLE_ARN="$AMB_DEVOPS_CODEBUILD_IAM_ROLE_ARN